#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & # Load Xresources
picom &			# picom for transparency
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
conky &                 # Load Clock widget
lxpanel &
nm-applet &
blueman-applet &
xfce4-power-manager &

# Set Caps to Mod/Escape
setxkbmap -option caps:super && killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape' &

# Properties button extra Mod/Escape
xmodmap -e 'keycode 135 = Super_R' &

